blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Cybozu Developer Community
    url: https://community.cybozu.dev/
    about: é–‹ç™ºè€…åŒå£«ã§è³ªå•ã‚„ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³ãŒã§ãã‚‹ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ ã§ã™ã€‚
  - name: ğŸŒ Kintone Developer Forum (è‹±èªç‰ˆã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£)
    url: https://forum.kintone.dev/
    about: Ask questions and discuss with other users in Kintone Developer Forum.
  - name: ğŸ“¤ API å°‚ç”¨ç›¸è«‡çª“å£
    url: https://jp.cybozu.help/k/ja/trouble_shooting/developer/developer_qa.html
    about: APIã®ä»•æ§˜ã«é–¢ã™ã‚‹ãŠå•ã„åˆã‚ã›ã¯ã“ã¡ã‚‰ã€‚
